### ISSUE TITLE
Circular import

### ISSUE THREAD

**Issue by raphaelramosds** [RRZE-HPC/pycachesim#18]
I am trying to run examples.py with

```bash
python examples.py
```
on `pycachesim` directory, but I've got this error

```bash
ImportError: cannot import name 'backend' from partially initialized module 'cachesim' (most likely due to a circular import)
```

I'm currently running windows 11 on my machine

**Comment by JanLJL** [comment]
Hi @raphaelramosds ,

if you run the `examples.py` script in the same directory as the `cachesim` directory, Python will check this directory first and the dependencies cannot be resolved properly unless you build the c backend first.

You have several options to make this work:
1. _(recommended)_ If you have pycachesim already installed (via `pip install .` or `python setup.py install`), you can just move the python script in a different directory where there is NO `cachesim` folder.
2. You can create the shared object file of `backend.c` yourself using any C compiler and providing the include and library paths to Python manually (e.g., `gcc -O3 -std=c99 -fPIC -c -I/path/to/pythonInclude/ cachesim/backend.c -o cachesim/backend.o && gcc -shared cachesim/backend.o -o cachesim/backend.so`), but the easiest way to achieve this is probably to run `python setup.py develop`, then you should see a .so file in the `cachesim` directory.

Hope this helps!

**Comment by raphaelramosds** [comment]
I tried the first option but my Microsoft Visual Studio version wasn't updated, so I got an error. But, I've remembered that I got Windows Subsystem for Linux so I could run cachesim without any problems
