### ISSUE TITLE
Steps to add a feature in the C backend

### ISSUE THREAD

**Issue by mahendraVamshi** [RRZE-HPC/pycachesim#19]
I want to add a feature to the backend and test it out with pycachesim. What are the steps that I need to follow for my changes to reflect in the python libs ? Do i have to recompile the backend into a shared-object every time I make a change ?

Any hellp will be appreciated. Thanks in advance.

**Comment by JanLJL** [comment]
Hi @mahendraVamshi ,

yes, if you make changes in the C backend, you need to recompile a new shared object to make those changes effective!
Please let us know in case you have any other questions!
