### ISSUE TITLE
There seems to be a logic error in cache block size checks

### ISSUE THREAD

**Issue by arkD** [RRZE-HPC/pycachesim#6]
in cache.py   Cashe.__init__() line ~293
        assert store_to is None or store_to.cl_size <= cl_size, \
            "cl_size may only increase towards main memory."
        assert load_from is None or load_from.cl_size <= cl_size, \
            "cl_size may only increase towards main memory."

if cl_size may only increase towards main memory then I expect
l1b = 32, l2b = 64, l3b =128 to work since l3 is closest to memory and l1 is furthest
but it does not
l1b = 128, l2b = 64, l3b =32 works
obviously these sizes are usually the same
but intuitively I think the comment is correct and the logic is wrong

**Comment by cod3monk** [comment]
I believe you're correct. I will fix this shortly. Thanks for reporting!
